image: node:20

pages:
  stage: deploy
  script:
    - npm ci
    - npm run build
    - rm -rf public
    - mv dist public
    - cp .fit-pages.yml public/
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
  only:
    - master